---
title: Mocking error responses
order: 74
---

When it comes to mocking an error response, it's recommended to compose a valid response using `res()` composition chain, rather than throwing an exception inside a request handler. This is mainly to distinguish between _internal_ and _intended_ exceptions.

<Hint mode="warning">
  Exception originating from a request handler is gracefully handled as a 500
  response from the Service Worker, but it's highly recommended{' '}
  <strong>to resolve it, as it indicates an error in your code</strong>.
</Hint>

By treating an error response as an actual response, and not an exception, you respect the standard and ensure your client code receives and handles a valid error response.

## Examples

Here's an example on how to mock an error response for the login `POST` request:

```js showLineNumbers
import { setupWorker, rest } from 'msw'

const worker = setupWorker(
  rest.post('/login', (req, res, ctx) => {
    const { username } = req.body

    return res(
      // Send a valid HTTP status code
      ctx.status(403),
      // And a response body, if necessary
      ctx.json({
        errorMessage: `User '${username}' not found`,
      }),
    )
  }),
)

worker.start()
```

<ResponsePreview
  request={{
    method: 'POST',
    url: '**/login**',
    body: `
{
  "username": "admin"
}
    `,
  }}
  response={{
    statusCode: 403,
    statusText: 'Forbidden',
    body: `
{
  "errorMessage": "User 'admin' not found"
}
    `,
  }}
/>
